<?php

namespace Database\Seeders;

use App\Enums\UserRole;
use App\Models\User;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UserCreateSeeder extends Seeder
{
    public function run(): void
    {
        User::create([
            'name' => 'Junayed Rahman Faiaz',
            'username' => 'Junayed-Rahman-Faiaz',
            'email' => 'admin@gmail.com',
            'profile_image' => 'images/profile_av.jpg',
            'role' => UserRole::SUPER_ADMIN->value,
            'password' => Hash::make('Abc@1234'),
        ]);

        $users = [
            "user",
            "Redwan Anjum",
            "Dina",
            // "Aditi Datta",
            // "Mostofa",
            // "Tamjid Khan",
            // "Jaber",
            // "Pritom",
            // "Shihan",
            // "Sharika",
            // "Adnan Maruf",
            // "reza taymur",
            // "Amena Siddique Mim",
            // "md polash",
            // "Mohammad Mahbubur Rahman",
            // "Sultana Sharmin",
            // "Md. Khairun Nobi",
            // "mobasshira Hossain",
            // "Lamia Rahim",
            // "Sayed Ranzu",
            // "Tanim",
            // "Joy Ahamed",
            // "md habib",
            // "Tyaba",
            // "Mahabubul Islam Tanvir",
            // "SIHAB",
            // "Zafrin",
            // "yusuf",
            // "Shawpan",
            // "Nafis",
            // "Md. Mehedi Hasan",
            // "Mojibur Rahman",
            // "Elora afrin",
            // "Dr Md Hassibul Hakam Ibn Samad",
            // "Mst.Momotaj akter",
            // "Shakil",
            // "Don Mithun Biswas",
            // "Nousheen",
            // "Md. Mahmudul Hasan",
            // "Shaddam Hossain",
            // "Tasnim khan",
            // "K. M. Nasir Uddin",
            // "Bandhan",
            // "HAMIDUL HAQUE bHUIYAN",
            // "md.yeasin",
            // "Hasanuzzaman Begh",
            // "Ali Hossain",
            // "Shakil Ahamed Raja",
            // "Tanvir Hasan",
            // "Rupa Zaman",
            // "Sukanna Das",
            // "Masud",
            // "Muhammad Anwarul Islam Babul",
            // "Farhana Dilshad",
            // "Farhana - Manik",
            // "Imran Khan",
            // "Mehedy Hasan",
            // "Juwel Rana",
            // "Md. Ashrafuzzaman",
            // "Kawsar Ahmed",
            // "Bappy",
            // "opu sarker",
            // "Israt Jahan",
            // "Irfanul Islam",
            // "Hasanuzzaman",
            // "Akib Mahfuz Haque",
            // "ayrine nipa",
            // "Dr.Shahinur Rahman",
            // "Ahmed Faiyaz Khan",
            // "Sujon Barman",
            // "ROKIBUL ISLAM",
            // "Hafsa Lajina",
            // "MD.MOZAMMEL HAQUE",
            // "Subaita",
            // "roktim",
            // "Hasib",
            // "Beli Akter",
            // "Md. Nurul",
            // "Md Hasibul Islam",
            // "Anik Sen",
            // "Sabbir Hossain sojib",
            // "zoa ahmed",
            // "Samina Rahman",
            // "Tahmima Begum",
            // "raju",
            // "Mahira Maliha",
            // "Rowshon kabir",
            // "Sabbir Ahmad Osmani",
            // "Syed Khurshed Zafri",
            // "Anika Tahsin",
            // "Minhaj Uddin",
            // "Sany Ahmed Al Imran",
            // "Samia islam",
            // "Simanto",
            // "Golam Sarwar",
            // "Abu javed",
            // "Rifat Sultana",
            // "Sharmiin Akter",
            // "alvi sabbir",
            // "diba",
            // "Saiful Islam",
            // "Zubayer Shihab",
            // "Wahifur Rahman Uhin",
            // "Nilima afrin",
            // "Maruf Hossain",
            // "Syed md Mohsin",
            // "Md. Yousuf Hassan Khan",
            // "Md.Rafiqul Islam Talukder",
            // "salma",
            // "Nabil hasan",
            // "md.alamin khan",
            // "Abdur Rahim",
            // "Shourave",
            // "Humayra Anjum",
            // "NAINA AFROSE ELAHI CHUMU",
            // "md Sumon",
            // "jahid sagor",
            // "Irfan Kabir",
            // "Fatha Asif",
            // "Afsana mim",
            // "Naushin surgical",
            // "Ayan Electronics Shop",
            // "Sabiya Mart",
            // "Tammim Shop",
            // "aangana",
            // "Classical Products BD",
            // "Cool & Gadget",
            // "Fashion Zone BD.",
            // "KASMIRI",
            // "Aysha Enterprise",
            // "T. M. Corporation",
            // "RM Gadget BD",
            // "Bdeshi Online Shop",
            // "shuchi",
            // "Zobyar Ahmed Palash",
            // "md",
            // "MD NURUZZAMAL",
            // "Mehedi hassan",
            // "A.k. Avi",
            // "Arafat Rahman",
            // "Shimul",
            // "Mahid",
            // "MD. SHAFAEATUL ISLAM SHIMUL",
            // "Md. Sarwar Jahan",
            // "shiful islam",
            // "M Nahidul Hasan",
            // "Ziaul Haq",
            // "Sadman Sakib Rohan",
            // "Sanjid Shahriar",
            // "shaminrooni sheikh",
            // "Tama",
            // "Samin Islam",
            // "MAHFUZUR RAHMAN",
            // "Morium sultana Jerin",
            // "Humayra sultana",
            // "SHameem Aarif",
            // "Taposh",
            // "samiya",
            // "Mirza Rakibul Islam",
            // "Md. Galib Ishraq Emran",
            // "Mr.Ripon",
            // "Tanmoy Sarker",
            // "Shreya",
            // "Md Abul Kalam Azad",
            // "Abdullah",
            // "Nurnabi",
            // "Arefin Junayed",
            // "zabid hasan",
            // "sayem ahmed",
            // "Yousuf Shafin",
            // "Maruf Khan",
            // "Alif",
            // "Bilkis Maya",
            // "Rafiul Hasan",
            // "Kamrul Fuad",
            // "Mahathe Hasan",
            // "Tasnim forkani",
            // "Liza",
            // "Ananya",
            // "Md. Kamrul Bari Rony",
            // "Mohiuddin Rana",
            // "Tanzil Ahmed",
            // "raznin",
            // "md.amanul hoque.",
            // "Emon Shanto",
            // "Joynal Abedeen",
            // "Anika Hassan",
            // "Wali Morshed",
            // "snigdha",
            // "rakib hasan",
            // "Engr Shameem",
            // "Shahanara Poly",
            // "Jubaer",
            // "Mansura Yesmin Nila",
            // "Mahbub Alam",
            // "Ahammed Tanvir",
            // "Monowar Ashraf khan",
            // "Sadia Haque",
            // "Khairul",
            // "Ferdaus Hasan",
            // "Shomik Maruf Siam",
            // "Mithun Das",
            // "Farhana Hossain",
            // "Md Mirajul Islam",
            // "Delwar Hossain",
            // "mahabur",
            // "silve",
            // "Sadia",
            // "Shamim",
            // "Tanvir Ahmed",
            // "MD NIAZ UDDIN",
            // "Farhan Ahmed",
            // "Junaid Affan",
            // "Rokunuzzaman",
            // "Tarun Sarker",
            // "Salman",
            // "lipi",
            // "MOHAMMAD FORHAD HALIM",
            // "Md. Alamgir Azad",
            // "Rasel",
            // "Mahfuz",
            // "Habib Al Saif",
            // "Rupanti Islam",
            // "Hasibul Hasan Khan",
            // "Rabbil",
            // "anangsha asmita hira",
            // "tawsia alam tuba",
            // "Shuchi khanom",
            // "tishadas",
            // "Md. aminul islam",
            // "Sharia Tasnim",
            // "fajlea rabby",
            // "tasnuva akter",
            // "noor mohammad",
            // "AymanShowrov",
            // "asma hossain",
            // "Mh Asif",
            // "Khan Muhammad",
            // "Farhat Hossain Tazim",
            // "Hossain",
            // "Abdul Aziz Miah",
            // "Md Robin",
            // "Hayder",
            // "Imran",
            // "Yusuf Ali",
            // "Enamul Islam",
            // "Ummey Kulsum Sadia",
            // "fahim uddin",
            // "Shadid Sarkar",
            // "Md sajedur Rahman",
            // "Suranjit",
            // "sayma ali ronti",
            // "Reshad",
            // "FARHAN",
            // "Abdur Rahman Siddique",
            // "Momo",
            // "Md. Monirul Ahsan",
            // "MD Arifuzzaman",
            // "Atia Nury",
            // "Rashedul islam",
            // "DR. MEHDI HASAN MAZUMDER",
            // "Munia Jahan",
            // "searajul Arafin",
            // "Meharun Nissa",
            // "Habib",
            // "babu",
            // "Ipshita hoque",
            // "afroza zahan",
            // "Mohammed saif uddin",
            // "Sabbir Ahmed",
            // "Eva",
            // "Obaidullah Ridwan",
            // "Tania Ahmed",
            // "RAIAN",
            // "Mohammed Nayeem Mollah",
            // "Leeon",
            // "Shahida Akter Bristy",
            // "bassira",
            // "samir",
            // "Jerin Haque",
            // "Mohd Moniruzzaman",
            // "Time Store",
            // "Unique Shoes BD",
            // "SSB Leather",
            // "Gazi Fashion Mall",
            // "New Smart Shoes",
            // "Dorji Mall",
            // "Dacca Shoes BD",
            // "Real Zones",
            // "SK Electronics",
            // "Avatech",
            // "Camera Hall",
            // "Sakiya Fashion",
            // "Aanggina Fashion",
            // "Veer Fashion Zone",
            // "Abi Texmart",
            // "Fashion BD Mart",
            // "Mariya Fashion BD",
            // "Minara Gallery",
            // "JS Watch World",
            // "Guaranty Super Shop",
            // "ROS Electronics",
            // "Best-Collection-BD",
            // "Fashion Wear bd..",
            // "Ma Dorbar Fashion",
            // "BEST TRIMMER AND SHAVER",
            // "Click Shopper",
            // "Golden Cart",
            // "Alpha Technology",
            // "Mh Store",
            // "Premier mart",
            // "Jakia Enterprise",
            // "SAILA HAIDER",
            // "Tariqul Islam",
            // "Salima sultana",
            // "Sarmin Akter",
            // "Omar Faruk",
            // "MD Mahir shahariayarb Alam",
            // "javed",
            // "Fahim",
            // "Lamia",
            // "Muein Al Azad",
            // "Nusrat Islam",
            // "Sharna Lata Debnath",
            // "MD HAFIZUR RAHAMAN",
            // "Mehjabin alam jeba",
            // "MOHAMMAD",
            // "A S M WALIUL HAQUE",
            // "Rony",
            // "adil ahnaf",
            // "robin",
            // "Anushmita Paul",
            // "redwan",
            // "rafaan",
            // "Safwan",
            // "Musawbir Al Wasi",
            // "Taufiqa Siddiqa",
            // "Alia Islam Shifa",
            // "Tumpa",
            // "Hasiv Md Musaddek",
            // "Shohely Chowdhury",
            // "Ayrun nahar",
            // "Manzurul Kabir",
            // "Mohsina Tabassum",
            // "Orthi",
            // "safin",
            // "Dr.Sheema Mahfuz",
            // "MUKIT",
            // "Ashik",
            // "sabbir rahman",
            // "Sajjad",
            // "Riyad",
            // "MD. Nurul Absar Siddique",
            // "Nayna",
            // "somrat islam emon",
            // "Ahnaf Amin Protik",
            // "Rubaia sharmin",
            // "Rumman",
            // "Ratul",
            // "Azmi",
            // "Ayasha Akter",
            // "Fatin Ishrak",
            // "Iren Choudhury",
            // "Ashik Alam",
            // "Sazzad Hossain",
            // "Rifat Hossain",
            // "Dr. kamruzzaman Shajal",
            // "Mumtahina",
            // "Muntasir Moni",
            // "Md. Bakthiyar Fatteh Niloy",
            // "Rezwan Rahat",
            // "MD.Zahurul Islam",
            // "Roksana Rashid",
            // "Ahnaf Ahmed",
            // "Rafiiiii",
            // "saiful",
            // "Motahar Hosen",
            // "Kanak",
            // "Bibi hazera",
            // "MD Imtiaz Ahammed",
            // "Sonia",
            // "Mohammad Nadimul Haque",
            // "S.M. Zubayer",
            // "Abdul Kadim",
            // "Rokeya Yeasmin",
            // "shaikh Saizad",
            // "Rajib",
            // "Shaikh Mohammad",
            // "Dr. fatema rubayat",
            // "Nusaiba Hassan",
            // "Sherazum",
            // "Maliha Mim",
            // "Md. Mamun Hossain",
            // "Faria Afrin",
            // "ujma begum",
            // "Mosharraf Hossain",
            // "abu sayem",
            // "Ashraf",
            // "Md Aminul Islam Masud",
            // "Khairul Islam Khandoker",
            // "Rauful",
            // "Ratna Akter",
            // "Fahima Chowdhury",
            // "Waquil Chowdhury Jim",
            // "Maruf",
            // "Afsana Alamgir Khan",
            // "Shimul Shahria Ahmed",
            // "MD Jahid hossain Rabbi",
            // "Farjana",
            // "shakib",
            // "Faija ahmed",
            // "kausik",
            // "Dalia Akther",
            // "Shemol Roy",
            // "Md Jinnat Ganim Mazumder",
            // "Asrafuzzaman Saif",
            // "Asraf Khan",
            // "ranu khanam",
            // "Asma Sadia",
            // "Md. Ehtesham Billah",
            // "Sourav Roy",
            // "Fahim Khan",
            // "Asma",
            // "Riya moni",
            // "Md Ripon",
            // "Mahadi Sunjid",
            // "Naureen",
            // "md Rone",
            // "Maimuna",
            // "Md Haris",
            // "Khan Muztaba",
            // "Chandana Islam",
            // "shaha aLom",
            // "Fatema Akter",
            // "Manus",
            // "farhana afroj",
            // "ARIFUL ISLAM",
            // "Zahir Haque",
            // "MD.Prince",
            // "abir Rahman",
            // "Md Abu Naser",
            // "Sarika Karim",
            // "Suruj khan",
            // "Ahsan Ahmed",
            // "Merazur Rahman",
            // "Raiyanul",
            // "Shehab",
            // "Fahima Akter",
            // "Ovee Ayesha",
            // "Abdul Kader",
            // "athena Chowdhury",
            // "Md. Ismail",
            // "kazi Islam",
            // "shovon",
            // "Khairul Islam Rajib",
            // "Nahiat Jahan",
            // "Aklima",
            // "raha mony",
            // "A.T.M.Zahidul Islam",
            // "Assrian Hasan Juman",
            // "Amena tower",
            // "newton",
            // "TANVIR HOSSEN",
            // "Rakib hosen",
            // "Jahid Hasan",
            // "Orpi",
            // "Mary",
            // "dr.rana",
            // "MUNNA NOMAN",
            // "Muntasir Ahmed Sahil",
            // "Omar Faruqe",
            // "sanjida akter",
            // "Meem R",
            // "Samiha Sofrana Azim",
            // "Foysal Hossain",
            // "Priam Talukder",
            // "Soniya akter",
            // "Mir Sifat",
            // "MD RIJWANUL AMIN",
            // "Mushfiqur Rahman Arnob",
            // "Md. Hassan",
            // "Godhuli Islam",
            // "Abir",
            // "Rafid",
            // "Ratan Miah",
            // "Faiza nubah",
            // "Suraiya",
            // "Zarif hasan",
            // "Afroza Akter",
            // "Mahmud Parvez Uzzal",
            // "abdullahal abrar",
            // "MD.Jalal Uddin Khna",
            // "zohura akter mithun",
            // "MD Mir Hossain",
            // "Md Anower Sadat Razib",
            // "S.M Arif",
            // "Sadi Zaman",
            // "Syed Serajus",
            // "Radif Hossain",
            // "md zakir",
            // "HAKIM FAISAL HOSSAIN",
            // "Amitav Roy",
            // "khorshadul Alam",
            // "Tavira Humayun Jitu",
            // "Md Sabbir ahmed",
            // "Kazi Yousuf",
            // "Sadman Sakib Khan",
            // "Md. khorshed Alam",
            // "Ayub Ali Mojumder",
            // "Mahzabin Nusrat Shifa",
            // "Rabeya Rahman",
            // "Mim Akter",
            // "tannim khandakar",
            // "Md naim ali",
            // "Sudipto",
            // "Subid R Sarkar",
            // "sarnajit paul",
            // "tahsina",
            // "Amin Miah",
            // "liga",
            // "ekra",
            // "maruf chowdhury",
            // "Khadija",
            // "rudro",
            // "Jannatul Tarisha",
            // "abu sufian",
            // "Kabir",
            // "Neaze Morshed Khan",
            // "atiqur rahman",
            // "Fariha Jannath",
            // "MD SHAHARIAR ALAM FAHID",
            // "SATTAJIT CHOWDHURY",
            // "Meherin islam",
            // "MD rubel ali",
            // "Mahmudul Hasan Joy",
            // "MD HUMAYUN KABIR",
            // "Sabrina Subah Nisa",
            // "Abidul Islam",
            // "Azizah",
            // "shajed",
            // "MOHON ISLAM",
            // "Khaled Al mamun",
            // "Kazi Noshin zaman",
            // "Sk Hridoy Shanto",
            // "Pori",
            // "Shahrukh",
            // "Rakib",
            // "DILRUBA AKTER LUNA",
            // "asif",
            // "rahat fameda refat",
            // "Rafi Rafi",
            // "Mahmuda Ibnat",
            // "Anika Anzum Zahin",
            // "Pavel",
            // "hamidur rahaman",
            // "Mohammad Fazlul Kabir",
            // "MD shuvo",
            // "Emtiaj Aaraf",
            // "B M Shaifullah",
            // "kowshik",
            // "Md Wahidul Islam",
            // "nasrin nila",
            // "Mehrab Hossain alvi",
            // "Mahrush Nafasat",
            // "Wasim",
            // "Wafiq",
            // "Lamia Farhin",
            // "Dhritiman Paul",
            // "SK.Rezaul Islam",
            // "Tasneem Tanha Ahona",
            // "sayla dewan",
            // "Dilip Kumar paul",
            // "hridoy",
            // "Farjana Akther",
            // "abdur rahman",
            // "md rana",
            // "Ashraful",
            // "Nowsher Tanim",
            // "Ramisha",
            // "Sanjida Urmi",
            // "towhid ahmed shimanto",
            // "Attiar Rahman",
            // "Zakir Hossain",
            // "SARIFUL ISLAM",
            // "Abul bashar",
            // "Santo",
            // "Ahsan Ul Kayum Bhuiya",
            // "Sadman",
            // "Faiyaz Hossen",
            // "DELOWAR",
            // "Asad Zaman",
            // "Koli",
            // "Miraz",
            // "jesmin akter",
            // "Razoana Ershad",
            // "MD Shifat",
            // "Ornob",
            // "Faria",
            // "Mohammad Ali Ekram",
            // "Mohsin Rubel",
            // "mobarak",
            // "Liza Sadia",
            // "Nobaira Mehreen Hassan",
            // "Billal Hossain",
            // "Tamanna Masoud",
            // "muhit",
            // "Md. Mohi Uddin Khan",
            // "Iftikharul Islam",
            // "Samira Akter",
            // "Inteha Rahman",
            // "Rimon",
            // "Dr Md Khorshed Alam",
            // "Manik Chandra Sutradhar",
            // "yesin",
            // "Shaila Noor",
            // "Shahinur Rahman",
            // "Shahriar Ahmed Shakib",
            // "Mihir Paul",
            // "Shahidul Islam",
            // "sadi",
            // "Inzamam Ul Haq",
            // "Humaira Akter",
            // "Mahdi Hasan",
            // "Md. Asaduzzaman",
            // "Gear Exact Bangladesh",
            // "Razib Imran",
            // "Shuvo",
            // "MD MOSHIUR RAHMAN",
            // "Shafiul Alam Sheaum",
            // "md Mobarak Hossain",
            // "tanveer hossain",
            // "MD TANVEER",
            // "Sanad Majumder",
            // "Mishkat Khandaker",
            // "Mahjuja Tayeeba",
            // "S M ABDULLAH AL NOMAN",
            // "Md Hafizur Rahman",
            // "Jishan",
            // "raya",
            // "Mahmud ahmed",
            // "rauf",
            // "sami nazrul islam",
            // "Masud Parvez",
            // "fazley rabbi",
            // "Umar Faruk",
            // "Farazi Shakil",
            // "Arif Uddin",
            // "MD Rabbi",
            // "Nibraj Mahid",
            // "Sharmin",
            // "Zubayer Hasan Raiyan",
            // "Masrafi Hasan",
            // "Md Monower Jahan",
            // "Nadis Iqbal Anas",
            // "Sakiba Efrana",
            // "Sakibul Hasan Sakib",
            // "ARCEUS",
            // "sabbir",
            // "Urmi akter",
            // "shahana khan",
            // "Shresta Biswas",
            // "Jannatul Ferdous Abonty",
            // "sabbir hasan",
            // "shajib",
            // "Refaz",
            // "Shohan",
            // "md rakib hossen",
            // "N/A",
            // "Syful islam",
            // "Joyanty",
            // "Ahosan Habib Raihan",
            // "Sajjad Husain",
            // "Md. Kazimul Hoque",
            // "Turjo",
            // "Md Jahid Hussain",
            // "Meharun Nisa",
            // "Mohammad Ismail",
            // "Anurath Barua",
            // "TM Muhaimen Haque",
            // "syed ahmed faruque",
            // "Fatema Tabassum",
            // "S M Masud Rana",
            // "Taslima",
            // "Tapashi Rabeya Bosree",
            // "Mostafizur",
            // "Shuja",
            // "Mehedi hasan anik",
            // "Rifat",
            // "nazrul ahmed",
            // "Bimal Barman",
            // "Md. Shajjad Shuvo",
            // "Shakhawat",
            // "Mohammad Sakib Chowdhury",
            // "Md. Sohel",
            // "Raihanul Islam Khan",
            // "akbar hossain",
            // "Ahsan habib",
            // "Naziah",
            // "Riva",
            // "Mim A",
            // "Fatin",
            // "md. jahangir",
            // "md sobuj islam",
            // "Shamalendu Debnath",
            // "Sifat",
            // "shirajul Munir",
            // "Md. Shamim Ahsan",
            // "Mahatab Hossain",
            // "Arnab Kumar Das",
            // "Md. Habibur Rahman",
            // "Omer Ferdous",
            // "taiba samiu",
            // "shirin akther",
            // "Molina",
            // "Farjana Rakhi",
            // "Shukla Datta",
            // "Mosaddek",
            // "Tishan Nur",
            // "Hafizul Haque",
            // "Asif Mahmud",
            // "Farzia Ahmed Bristy",
            // "Sadia Rahman",
            // "tahrima",
            // "Srabanti Singha",
            // "Riad Hassan",
            // "Sk Mashuk",
            // "Jewel",
            // "Amit Ghosh",
            // "debashis",
            // "Md.Zahid Hossain",
            // "farhana",
            // "Humaira",
            // "Khandaker Mostafa Zaman Milton",
            // "Dr.Anika",
            // "Adnan khan",
            // "Shakira Sharothi",
            // "sadi sarmin chowdhury",
            // "sahanaz akter soma",
            // "rasel ahmed",
            // "Naimul Hasan Priyom",
            // "Farhan Shamit",
            // "MD. ABU UBAYDA",
            // "Shahazada Raihan",
            // "Lenin",
            // "khadija akther",
            // "Mr. Anowarul Arif Khan",
            // "Soumik Kanti Barua",
            // "Mahbubul",
            // "zahid",
            // "Shanaz Shanta",
            // "Ataur",
            // "Mahbub Hossain",
            // "Md hannan",
            // "Fahim Alam",
            // "Md Mominur Rahman",
            // "sajib das",
            // "NurAlam",
            // "S.M. Ishraqur Rahman",
            // "oaj uddin tonmoy",
            // "Ismail",
            // "Faysal",
            // "Zubayer",
            // "jainab binte mohib",
            // "Mohammed Athlo Islam",
            // "Kazi Redwan",
            // "RASEL KHAN",
            // "Ruku",
            // "Md Omor Faruk",
            // "Tazvir",
            // "shifa",
            // "Raatba Aziz",
            // "Afrin Sultana",
            // "piya chowdhury",
            // "Labonno",
            // "emroz",
            // "Md Adnan Islam Sayef",
            // "KHAIRUL ISLAM",
            // "Mehdi Mosabbir",
            // "Safa Sadia",
            // "Islam Arif",
            // "Tasnim Hossain Nihim",
            // "Sanjida",
            // "Rowda Tahrim",
            // "Rafi",
            // "waheeda tasnim",
            // "Nawmee naahrin",
            // "Md.Masum",
            // "Md. Tarekul Islam",
            // "Quazi Sami Ul Islam",
            // "md alamin",
            // "Shovan Debnath",
            // "Kazi Tahsin Tamim",
            // "sobuj",
            // "Armina Hossain",
            // "Md.mohosin",
            // "Tarpi",
            // "Belal",
            // "MD Nazrul Islam",
            // "Saeed Al Hasan",
            // "NAZMUZ SAKIB",
            // "amirul islam",
            // "jannatul mawa ilmi",
            // "mishkat labib",
            // "Apon",
            // "Oney Tabassum",
            // "papia sultana popy",
            // "jamal",
            // "Ramim",
            // "md noyon",
            // "Abrar",
            // "Asaduzzaman",
            // "S.M.Tajwal Huda Dip",
            // "Sharmin akter happy",
            // "natasha sharif",
            // "innocent solyman",
            // "Mamun",
            // "Samanta",
            // "Abul hussain",
            // "Istisk Ahmed",
            // "Nayef",
            // "nita",
            // "Farhana Mojib",
            // "Kohinoor Akhter",
            // "Anjuna Rumman",
            // "Imran Faisal",
            // "taspia tasrin",
            // "ayon sen",
            // "Syad Masud",
            // "Farhad",
            // "mukta",
            // "tonmoy",
            // "Isaba",
            // "Tanisha",
            // "K.M.Zubayer Ali",
            // "Jaima tahsin keya",
            // "Md. Jahir Uddin Babar",
            // "Nazmul hasan",
            // "Tanvir Apurbo",
            // "Top Bangla",
            // "Family Life",
            // "SAMIR Fashion",
            // "E Store Online BD",
            // "Ariz Trade Shop",
            // "Imam Telecom",
            // "Dream Haramain",
            // "Raisa Auto House",
            // "Beauty Style",
            // "Save Bazaar",
            // "Fashion Fub BD",
            // "RaFi Beauty Shop",
            // "wanju my",
            // "Islamic Super Shop",
            // "Handicraft Shop",
            // "Biker's Decorum",
            // "Goo Gadget",
            // "Gadget Zone Bd",
            // "Femelabd",
            // "The Splash Bd",
            // "GADGET FIJ",
            // "Covered Cases & Accessories",
            // "Barira Enterprise",
            // "REX MOLL",
            // "Style&Smile Fashion",
            // "E-Beehive.",
            // "BD New Collection",
            // "Magical All Fashion",
            // "Shoes Plaza",
            // "Mother Pray Shop",
            // "Somiron Online Shop",
            // "Mehzabin beauty store",
            // "JK Enterprise kiosk",
            // "Smart Fashion Mall",
            // "MHS SUNNAH SHOP",
            // "New RS Fashion House",
            // "Somiron Electronics",
            // "The China Bag House",
            // "The China Shopping Zone BD",
            // "SH Gadget",
            // "Ayesha International",
            // "Galaxy Health Care",
            // "Shayan Fashion House",
            // "M.C.S",
            // "JS DREEM POINT",
            // "Priyangon Texmart",
            // "Falak Texmart",
            // "Home Edge",
            // "Purple Fashion BD",
            // "Digital Vape House",
            // "Anser Enterprise",
            // "Fashion Collection BD",
            // "Alok Mart BD",
            // "Trunk",
            // "ONE MORE.",
            // "Online Trusted Organization",
            // "NEW ASHA CAR DECORATION",
            // "Jonaki Fashion BD",
            // "Saree Bitan",
            // "Queenly demand",
            // "Shaver Shop Bangladesh",
            // "Premier Shop",
            // "Trendio",
            // "Md Shahriar Razu",
            // "Anika Tasnim",
            // "Avijit Roy",
            // "MD. Foyzul Islam",
            // "Nurul Amin",
            // "Shadman haque",
            // "Tanvir Ahammed",
            // "Sarwar Ahmed",
            // "Mushfiq Aziz",
            // "Mohiuddin Azad",
            // "Ganendrana Nath",
            // "Rezwan",
            // "Dr. Zubair Ahmed",
            // "tomalika saha",
            // "MAHBUB HOSSAIN SADI",
            // "boni amin",
            // "ANM SALAHUDDIN",
            // "popy Sheikh",
            // "Samiul Basar",
            // "Tinon Turja",
            // "N.Islam",
            // "Tahmid Ayman",
            // "Nazneen Sayeed Nishat",
            // "orpo",
            // "ani aronneya",
            // "Ashiqur Rahman",
            // "Tanmya hussain",
            // "Nasir ahmed joy",
            "papan"
        ];

        foreach ($users as $user) {
            User::create([
                'name' => strtolower($user),
                'username' => User::generateUniqueUsername($user),
                'email' => strtolower($user) . '@gmail.com',
                'profile_image' => 'images/user/' . rand(1, 15) . '.jpg',
                'role' => UserRole::USER->value,
                'password' => Hash::make('Abc@1234'),
                'remember_token' => Str::random(10),
            ]);
        }
    }
}
